language: node_js
node_js:
  - node

sudo: required

services:
  - docker

before_script:
  - yarn run travis

script:
  - yarn run start

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - ./scripts/ci-deployment/docker_ci.sh
