sudo: required

services:
  - docker

env:
  global:
  - DOCKER_REPO=nhsuk/profiles-db
  - DOCKER_USERNAME=nhsukautomata

script:
  - npm run test

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - ./ci-deployment/docker_ci.sh

