language: node_js
node_js:
  - node

sudo: required

services:
  - docker

script:
  - npm run test

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - ./ci-deployment/docker_ci.sh
