language: node_js
node_js:
  - node

sudo: required

services:
  - docker

script:
  - yarn run git-hooks

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - ./scripts/ci-deployment/docker_ci.sh
