language: node_js
node_js: node
cache: yarn
services: docker

before_install: yarn global add greenkeeper-lockfile@1

before_script:
  - yarn run travis
  - greenkeeper-lockfile-update

script: yarn run start

after_script: greenkeeper-lockfile-upload

after_success: bash ./scripts/ci-deployment/deploy.sh
