version: '2'

services:

  profiles-db:
    image: "nhsuk/profiles-db:${DOCKER_IMAGE_TAG}"
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label_soft: c2s=true
    logging:
      driver: splunk
      options:
        splunk-url: ${SPLUNK_HEC_URL}
        splunk-token: ${SPLUNK_HEC_TOKEN}
        splunk-insecureskipverify: "true"
        splunk-sourcetype: docker
        splunk-source: profiles-db
        splunk-verify-connection: "false"
        tag: '{{.ImageName}} {{.Name}} {{.FullID}}'
        splunk-format: json
